//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanbooruDownloader3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanbooruDownloader3.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Tag.
        /// </summary>
        internal static string ArtistTag {
            get {
                return ResourceManager.GetString("ArtistTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch job completed!.
        /// </summary>
        internal static string BatchCompleted {
            get {
                return ResourceManager.GetString("BatchCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting batch job.
        /// </summary>
        internal static string BatchStarting {
            get {
                return ResourceManager.GetString("BatchStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch job stopped..
        /// </summary>
        internal static string BatchStopped {
            get {
                return ResourceManager.GetString("BatchStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping batch jobs....
        /// </summary>
        internal static string BatchStopping {
            get {
                return ResourceManager.GetString("BatchStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters in the filename format not allowed..
        /// </summary>
        internal static string CharactersNotAllowed {
            get {
                return ResourceManager.GetString("CharactersNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Tag.
        /// </summary>
        internal static string CharacterTag {
            get {
                return ResourceManager.GetString("CharacterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Tag.
        /// </summary>
        internal static string CircleTag {
            get {
                return ResourceManager.GetString("CircleTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Tag.
        /// </summary>
        internal static string CopyrightTag {
            get {
                return ResourceManager.GetString("CopyrightTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting temporary file:.
        /// </summary>
        internal static string DeletingTempFile {
            get {
                return ResourceManager.GetString("DeletingTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete!.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading post #.
        /// </summary>
        internal static string DownloadingPost {
            get {
                return ResourceManager.GetString("DownloadingPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading:.
        /// </summary>
        internal static string DownloadingUrl {
            get {
                return ResourceManager.GetString("DownloadingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download List.
        /// </summary>
        internal static string DownloadList {
            get {
                return ResourceManager.GetString("DownloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already on first page!.
        /// </summary>
        internal static string ErrorFirstPage {
            get {
                return ResourceManager.GetString("ErrorFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create long file name {0}!\r\n{1}.
        /// </summary>
        internal static string ErrorLongFileName {
            get {
                return ResourceManager.GetString("ErrorLongFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Parsing Port.
        /// </summary>
        internal static string ErrorParsingPort {
            get {
                return ResourceManager.GetString("ErrorParsingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous page information..
        /// </summary>
        internal static string ErrorPrevPageInfo {
            get {
                return ResourceManager.GetString("ErrorPrevPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faults Tag.
        /// </summary>
        internal static string FaultsTag {
            get {
                return ResourceManager.GetString("FaultsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists!.
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Tag.
        /// </summary>
        internal static string GeneralTag {
            get {
                return ResourceManager.GetString("GeneralTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image ID.
        /// </summary>
        internal static string ImageId {
            get {
                return ResourceManager.GetString("ImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Limit.
        /// </summary>
        internal static string ImageLimit {
            get {
                return ResourceManager.GetString("ImageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Rating.
        /// </summary>
        internal static string ImageRating {
            get {
                return ResourceManager.GetString("ImageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Tags.
        /// </summary>
        internal static string ImageTags {
            get {
                return ResourceManager.GetString("ImageTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get Image URL, restricted tags?.
        /// </summary>
        internal static string ImageUrlFailed {
            get {
                return ResourceManager.GetString("ImageUrlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File URL resolved!.
        /// </summary>
        internal static string ImageUrlResolved {
            get {
                return ResourceManager.GetString("ImageUrlResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format..
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid preferred method!.
        /// </summary>
        internal static string InvalidMethod {
            get {
                return ResourceManager.GetString("InvalidMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page value: {0}.
        /// </summary>
        internal static string InvalidPageValue {
            get {
                return ResourceManager.GetString("InvalidPageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Port Number:.
        /// </summary>
        internal static string InvalidPortNumber {
            get {
                return ResourceManager.GetString("InvalidPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL:.
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value:.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid limit value: {0}.
        /// </summary>
        internal static string LimitInvalid {
            get {
                return ResourceManager.GetString("LimitInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image limit too high! Setting back to {0}..
        /// </summary>
        internal static string LimitTooHigh {
            get {
                return ResourceManager.GetString("LimitTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Page.
        /// </summary>
        internal static string ListPage {
            get {
                return ResourceManager.GetString("ListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading next page....
        /// </summary>
        internal static string LoadingNextPage {
            get {
                return ResourceManager.GetString("LoadingNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum filename length exceeding limit ({0}). This might cause the file cannot be saved, continue?.
        /// </summary>
        internal static string MaxFilenameExceeded {
            get {
                return ResourceManager.GetString("MaxFilenameExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 Hash.
        /// </summary>
        internal static string Md5Hash {
            get {
                return ResourceManager.GetString("Md5Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image to download!.
        /// </summary>
        internal static string NoImageToDownload {
            get {
                return ResourceManager.GetString("NoImageToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No posts!.
        /// </summary>
        internal static string NoPosts {
            get {
                return ResourceManager.GetString("NoPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags.xml, need to download!.
        /// </summary>
        internal static string NoTagsError {
            get {
                return ResourceManager.GetString("NoTagsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags.xml Error.
        /// </summary>
        internal static string NoTagsErrorCaption {
            get {
                return ResourceManager.GetString("NoTagsErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to continue..
        /// </summary>
        internal static string OkContinue {
            get {
                return ResourceManager.GetString("OkContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Filename.
        /// </summary>
        internal static string OriginalFilename {
            get {
                return ResourceManager.GetString("OriginalFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent:.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Batch Job.
        /// </summary>
        internal static string PauseBatch {
            get {
                return ResourceManager.GetString("PauseBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post is deleted..
        /// </summary>
        internal static string PostUrlDeleted {
            get {
                return ResourceManager.GetString("PostUrlDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No post parser for provider:.
        /// </summary>
        internal static string PostUrlNoParser {
            get {
                return ResourceManager.GetString("PostUrlNoParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid file_url, probably deleted..
        /// </summary>
        internal static string PostUrlNoValid {
            get {
                return ResourceManager.GetString("PostUrlNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still loading post url, try again later..
        /// </summary>
        internal static string PostUrlStillLoading {
            get {
                return ResourceManager.GetString("PostUrlStillLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev Page.
        /// </summary>
        internal static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        internal static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query URL:.
        /// </summary>
        internal static string QueryUrl {
            get {
                return ResourceManager.GetString("QueryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Batch Job.
        /// </summary>
        internal static string ResumeBatch {
            get {
                return ResourceManager.GetString("ResumeBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Folder.
        /// </summary>
        internal static string SaveFolder {
            get {
                return ResourceManager.GetString("SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tag.
        /// </summary>
        internal static string SearchTag {
            get {
                return ResourceManager.GetString("SearchTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select save folder!.
        /// </summary>
        internal static string SelectSaveFolder {
            get {
                return ResourceManager.GetString("SelectSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download skipped, ID:.
        /// </summary>
        internal static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download skipped, contains blacklisted tag: {0}.
        /// </summary>
        internal static string SkippedBlacklistedTag {
            get {
                return ResourceManager.GetString("SkippedBlacklistedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download skipped, file exists:.
        /// </summary>
        internal static string SkippedExists {
            get {
                return ResourceManager.GetString("SkippedExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download skipped, file extension: {0} doesn&apos;t match with filter: {1} in url {2}..
        /// </summary>
        internal static string SkippedFilter {
            get {
                return ResourceManager.GetString("SkippedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download skipped, file extension: {0} matching with filter: {1} (Exclude Mode) in url {2}..
        /// </summary>
        internal static string SkippedFilterExclude {
            get {
                return ResourceManager.GetString("SkippedFilterExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load list..
        /// </summary>
        internal static string StatusCantLoadList {
            get {
                return ResourceManager.GetString("StatusCantLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identical list, probably last page..
        /// </summary>
        internal static string StatusIdenticalList {
            get {
                return ResourceManager.GetString("StatusIdenticalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more images..
        /// </summary>
        internal static string StatusNoMoreImages {
            get {
                return ResourceManager.GetString("StatusNoMoreImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing....
        /// </summary>
        internal static string StatusPausing {
            get {
                return ResourceManager.GetString("StatusPausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming....
        /// </summary>
        internal static string StatusResuming {
            get {
                return ResourceManager.GetString("StatusResuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still downloading!.
        /// </summary>
        internal static string StillDownloading {
            get {
                return ResourceManager.GetString("StillDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count.
        /// </summary>
        internal static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Date/Time.
        /// </summary>
        internal static string UploadDateTime {
            get {
                return ResourceManager.GetString("UploadDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to open too many images (&gt;5), proceed?.
        /// </summary>
        internal static string WarningManyImages {
            get {
                return ResourceManager.GetString("WarningManyImages", resourceCulture);
            }
        }
    }
}
